const tattooStyles = [
  '3D',
  'Árabes',
  'Aztecas',
  'Acuarelas',
  'Ambigramas',
  'Anatómicos',
  'Arte Pop',
  'Biomecánicos',
  'Black work',
  'Black & Grey',
  'Blastover',
  'Brush o avantgarde',
  'Bosquejos',
  'Color',
  'Célticos',
  'Degradados',
  'Espacio negativo',
  'Explosiones',
  'Egipcios',
  'Flechas',
  'Fluorecentes',
  'Geométricos',
  'Glifos',
  'Glitch/Distorcionado',
  'Graffitis',
  'Góticos',
  'Handpoked',
  'Hawaianos',
  'Hindúes',
  'Híper realista',
  'Ilusión óptica',
  'Invertidos',
  'Japonéses',
  'Letras/Lettering',
  'Lineas',
  'Maories',
  'Mambos',
  'Mandalas',
  'Mayas',
  'Minimalistas',
  'Neo tradicional',
  'Nueva escuela',
  'Nórdicos',
  'Números romanos',
  'Ornamental',
  'Pixeles',
  'Puntillismo',
  'Realistas',
  'Retratos',
  'Siluetas',
  'Sombras',
  'Surrealistas',
  'Tinta blanca',
  'Tinta ultravioleta',
  'Trash Polka',
  'Tradicional americano',
  'Tradicional japonés',
  'Tribales',
  'Una línea',
  'Vieja escuela',
  'Vikingos',
]

const todos = [
  'Sombras',
  'Realistas',
  'Tribales',
  'Graffitis',
  'Góticos',
  'Letras/Lettering',
  'Geométricos',
  'Puntillismo',
  'Flechas',
  'Glifos',
  'Números romanos',
  'Acuarelas',
  'Black work',
  'Tradicionales',
  'Tinta blanca',
  'Surrealistas',
  'Bosquejos',
  'Siluetas',
  'Retratos',
  'Arte Pop',
  'Pixeles',
  'Nórdicos',
  'Nueva escuela',
  'Neo tradicional',
  'Espacio negativo',
  'Minimalistas',
  'Mayas',
  'Mandalas',
  'Mambos',
  'Lineas',
  'Japonéses',
  'Invertidos',
  'Híper realista',
  'Degradados',
  'Tinta ultravioleta',
  'Glitch/Distorcionado',
  'Célticos',
  'Explosiones',
  'Biomecánicos',
  'Anatómicos',
  'Ambigramas',
  'Resumenes',
  '3D',
  'Ilusión óptica',
  'Vieja escuela',
  '',
]

export default tattooStyles
