const tattooStyles = [
  'Color',
  'Vieja escuela',
  'Sombras',
  'Realistas',
  'Tribales',
  'Graffitis',
  'Góticos',
  'Letras/Lettering',
  'Geométricos',
  'Puntillismo',
  'Flechas',
  'Glifos',
  'Números romanos',
  'Acuarelas',
  'Black work',
  'Tradicionales',
  'Tinta blanca',
  'Surrealistas',
  'Bosquejos',
  'Siluetas',
  'Retratos',
  'Arte Pop',
  'Pixeles',
  'Nórdicos',
  'Nueva escuela',
  'Neo tradicional',
  'Espacio negativo',
  'Minimalistas',
  'Mayas',
  'Mandalas',
  'Mambos',
  'Lineas',
  'Japonéses',
  'Invertidos',
  'Híper realista',
  'Degradados',
  'Tinta ultravioleta',
  'Glitch/Distorcionado',
  'Célticos',
  'Explosiones',
  'Biomecánicos',
  'Anatómicos',
  'Ambigramas',
  '3D',
  'Ilusión óptica',
]

const todos = [
  'Sombras',
  'Realistas',
  'Tribales',
  'Graffitis',
  'Góticos',
  'Letras/Lettering',
  'Geométricos',
  'Puntillismo',
  'Flechas',
  'Glifos',
  'Números romanos',
  'Acuarelas',
  'Black work',
  'Tradicionales',
  'Tinta blanca',
  'Surrealistas',
  'Bosquejos',
  'Siluetas',
  'Retratos',
  'Arte Pop',
  'Pixeles',
  'Nórdicos',
  'Nueva escuela',
  'Neo tradicional',
  'Espacio negativo',
  'Minimalistas',
  'Mayas',
  'Mandalas',
  'Mambos',
  'Lineas',
  'Japonéses',
  'Invertidos',
  'Híper realista',
  'Degradados',
  'Tinta ultravioleta',
  'Glitch/Distorcionado',
  'Célticos',
  'Explosiones',
  'Biomecánicos',
  'Anatómicos',
  'Ambigramas',
  'Resumenes',
  '3D',
  'Ilusión óptica',
  'Vieja escuela',
  '',
]

export default tattooStyles
